# Generated by Django 5.1.3 on 2024-11-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ip_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ip_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
